name: Update EWS Data

on:
  schedule:
    - cron: '0 6 * * 1'  # wekelijks maandagochtend om 6u
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2

    - name: Installeer R-packages
      run: |
        Rscript -e 'install.packages(c("curl", "readr", "dplyr", "sf", "stringr", "rgbif", "leaflet"))'

    - name: Run RIPARIAS WFS script
      run: Rscript src/riparias_download.R

    - name: Upload geopackages
      uses: actions/upload-artifact@v4
      with:
        name: ews-outputs
        path: data/output/*.gpkg