name: Update EWS Data

on:
  schedule:
    - cron: '0 6 * * 1'  # wekelijks maandagochtend om 6u
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2

    - name: Installeer R-packages
      run: |
        Rscript -e 'install.packages(c("curl", "readr", "dplyr", "sf", "stringr", "rgbif", "leaflet"))'

    - name: Run RIPARIAS WFS script
      run: Rscript src/riparias_download.R

    - name: Verwijder oude bestanden (>6)
      run: |
        cd data/output
        ls -tp | grep -v '/$' | tail -n +7 | xargs -d '\n' rm -f --

    - name: Commit en push output
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add data/output/*.gpkg
        git commit -m "Update output: $(date +'%Y-%m-%d')" || echo "Geen wijzigingen."
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}